-- SQL MIGRATION: ADD ACTION AND DESCRIPTION FIELDS TO PUBLIC.SCORES
ALTER TABLE public.scores ADD COLUMN IF NOT EXISTS action text DEFAULT 'manual_log';
ALTER TABLE public.scores ADD COLUMN IF NOT EXISTS description text DEFAULT '';
